/*
 * This source file was generated by the Gradle 'init' task
 */
package vacancy_tracker;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class);

//        ConfigurableApplicationContext context = SpringApplication.run(App.class, args);
//        System.out.println("Application started");

//        var service = context.getBean(TrudVsemVacanciesService.class);
//        var client = context.getBean(TrudVsemApiClient.class);
//
//        System.out.println( client.searchVacancies(VacancySearchFilter.builder()
//        .build()));
//        System.out.println(service.isAvailable());

//        var service = context.getBean(SuperJobVacanciesService.class);
//        var future = service.search("");
//
//        future.thenAccept(vacancies -> vacancies.forEach(System.out::println));
    }
}
