/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.springframework.boot") version "3.2.5"
    id("io.spring.dependency-management") version "1.1.5"
}

repositories {
    mavenCentral()
}

val lombokVersion = "1.18.44"
val mapstructVersion = "1.6.3"
val telegramVersion = "10.0.0"
val lombokMapstruct = "0.2.0"

dependencies {

    compileOnly("org.projectlombok:lombok:$lombokVersion")

    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:$lombokMapstruct")

    annotationProcessor("org.mapstruct:mapstruct-processor:$mapstructVersion")

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")

    implementation("org.telegram:telegrambots-springboot-longpolling-starter:$telegramVersion")
    implementation("org.telegram:telegrambots-client:$telegramVersion")

    implementation("org.mapstruct:mapstruct:$mapstructVersion")

    implementation("org.liquibase:liquibase-core")

    implementation(libs.guava)

    runtimeOnly("org.postgresql:postgresql")
    testImplementation(libs.junit)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "vacancy_tracker.App"
}