logging:
  level:
    vacancy_tracker: DEBUG

server:
  port: 8088

#Задать в конфигурации
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

superjob:
  appId: ${SUPER_JOB_APP_ID}
  secretKey: ${SUPER_JOB_SECRET}
  api:
    vacanciesUrl: https://api.superjob.ru/2.0/vacancies
    companiesUrl: https://api.superjob.ru/2.0/clients
    regionsUrl: https://api.superjob.ru/2.0/regions
    citiesUrl: https://api.superjob.ru/2.0/towns

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacancy_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml